FROM node:16-alpine As initial
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
FROM node:16-alpine As final
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm set-script prepare ""
RUN npm install --omit=dev
COPY . .
COPY --from=initial /usr/src/app/dist ./dist
CMD npm run start:dev