export const Constants = {
  MIN_RATING_VALUE: 1,
  MAX_RATING_VALUE: 5,
  MIN_P2W_VALUE: 1,
  MAX_P2W_VALUE: 5,
  MIN_COMMENT_CHARACTERS: 1,
  MAX_COMMENT_CHARACTERS: 250,
  KAFKA_CONSUMER_GROUP_ID: "reviews-consumer",
  KAFKA_CLIENT_ID: "reviews",
};
